;;;; By Nikodemus Siivola <nikodemus@random-state.net>, 2012.
;;;;
;;;; Permission is hereby granted, free of charge, to any person
;;;; obtaining a copy of this software and associated documentation files
;;;; (the "Software"), to deal in the Software without restriction,
;;;; including without limitation the rights to use, copy, modify, merge,
;;;; publish, distribute, sublicense, and/or sell copies of the Software,
;;;; and to permit persons to whom the Software is furnished to do so,
;;;; subject to the following conditions:
;;;;
;;;; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
;;;; EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
;;;; MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
;;;; IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
;;;; CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
;;;; TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
;;;; SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

(in-package :sb-external-format)

;;;; Perhaps controversially, for LATIN formats we canonicalize on the more
;;;; memorable name, LATIN N, and not the official ISO name, which are harder
;;;; for humans to recognize at a glance.
;;;;
;;;; FIXME: Ideally we'd really like to report the names in error messages
;;;; along the lines of "LATIN 1 (ISO 8859-1)".

;;;; LATIN 1

(define-character-encoding :latin-1
  (:nicknames :latin1 :iso-8859-1 :iso8859-1)
  (:repertoire (0 . 255))
  (:binary t))

(define-unibyte-encoder :latin-1 (char-code)
  (if (> char-code 255)
      (handle-error)
      char-code))

(define-unibyte-decoder :latin-1 (octet)
  (if (> octet 255)
      (handle-error)
      octet))

;;;; LATIN 2

(define-character-encoding :latin-2
  (:nicknames :latin2 :iso-8859-2 :iso8859-2)
  (:binary t))

(define-unibyte-mapping :latin-2
  (#xA1 #x0104) ; LATIN CAPITAL LETTER A WITH OGONEK
  (#xA2 #x02D8) ; BREVE
  (#xA3 #x0141) ; LATIN CAPITAL LETTER L WITH STROKE
  (#xA5 #x013D) ; LATIN CAPITAL LETTER L WITH CARON
  (#xA6 #x015A) ; LATIN CAPITAL LETTER S WITH ACUTE
  (#xA9 #x0160) ; LATIN CAPITAL LETTER S WITH CARON
  (#xAA #x015E) ; LATIN CAPITAL LETTER S WITH CEDILLA
  (#xAB #x0164) ; LATIN CAPITAL LETTER T WITH CARON
  (#xAC #x0179) ; LATIN CAPITAL LETTER Z WITH ACUTE
  (#xAE #x017D) ; LATIN CAPITAL LETTER Z WITH CARON
  (#xAF #x017B) ; LATIN CAPITAL LETTER Z WITH DOT ABOVE
  (#xB1 #x0105) ; LATIN SMALL LETTER A WITH OGONEK
  (#xB2 #x02DB) ; OGONEK
  (#xB3 #x0142) ; LATIN SMALL LETTER L WITH STROKE
  (#xB5 #x013E) ; LATIN SMALL LETTER L WITH CARON
  (#xB6 #x015B) ; LATIN SMALL LETTER S WITH ACUTE
  (#xB7 #x02C7) ; CARON
  (#xB9 #x0161) ; LATIN SMALL LETTER S WITH CARON
  (#xBA #x015F) ; LATIN SMALL LETTER S WITH CEDILLA
  (#xBB #x0165) ; LATIN SMALL LETTER T WITH CARON
  (#xBC #x017A) ; LATIN SMALL LETTER Z WITH ACUTE
  (#xBD #x02DD) ; DOUBLE ACUTE ACCENT
  (#xBE #x017E) ; LATIN SMALL LETTER Z WITH CARON
  (#xBF #x017C) ; LATIN SMALL LETTER Z WITH DOT ABOVE
  (#xC0 #x0154) ; LATIN CAPITAL LETTER R WITH ACUTE
  (#xC3 #x0102) ; LATIN CAPITAL LETTER A WITH BREVE
  (#xC5 #x0139) ; LATIN CAPITAL LETTER L WITH ACUTE
  (#xC6 #x0106) ; LATIN CAPITAL LETTER C WITH ACUTE
  (#xC8 #x010C) ; LATIN CAPITAL LETTER C WITH CARON
  (#xCA #x0118) ; LATIN CAPITAL LETTER E WITH OGONEK
  (#xCC #x011A) ; LATIN CAPITAL LETTER E WITH CARON
  (#xCF #x010E) ; LATIN CAPITAL LETTER D WITH CARON
  (#xD0 #x0110) ; LATIN CAPITAL LETTER D WITH STROKE
  (#xD1 #x0143) ; LATIN CAPITAL LETTER N WITH ACUTE
  (#xD2 #x0147) ; LATIN CAPITAL LETTER N WITH CARON
  (#xD5 #x0150) ; LATIN CAPITAL LETTER O WITH DOUBLE ACUTE
  (#xD8 #x0158) ; LATIN CAPITAL LETTER R WITH CARON
  (#xD9 #x016E) ; LATIN CAPITAL LETTER U WITH RING ABOVE
  (#xDB #x0170) ; LATIN CAPITAL LETTER U WITH DOUBLE ACUTE
  (#xDE #x0162) ; LATIN CAPITAL LETTER T WITH CEDILLA
  (#xE0 #x0155) ; LATIN SMALL LETTER R WITH ACUTE
  (#xE3 #x0103) ; LATIN SMALL LETTER A WITH BREVE
  (#xE5 #x013A) ; LATIN SMALL LETTER L WITH ACUTE
  (#xE6 #x0107) ; LATIN SMALL LETTER C WITH ACUTE
  (#xE8 #x010D) ; LATIN SMALL LETTER C WITH CARON
  (#xEA #x0119) ; LATIN SMALL LETTER E WITH OGONEK
  (#xEC #x011B) ; LATIN SMALL LETTER E WITH CARON
  (#xEF #x010F) ; LATIN SMALL LETTER D WITH CARON
  (#xF0 #x0111) ; LATIN SMALL LETTER D WITH STROKE
  (#xF1 #x0144) ; LATIN SMALL LETTER N WITH ACUTE
  (#xF2 #x0148) ; LATIN SMALL LETTER N WITH CARON
  (#xF5 #x0151) ; LATIN SMALL LETTER O WITH DOUBLE ACUTE
  (#xF8 #x0159) ; LATIN SMALL LETTER R WITH CARON
  (#xF9 #x016F) ; LATIN SMALL LETTER U WITH RING ABOVE
  (#xFB #x0171) ; LATIN SMALL LETTER U WITH DOUBLE ACUTE
  (#xFE #x0163) ; LATIN SMALL LETTER T WITH CEDILLA
  (#xFF #x02D9) ; DOT ABOVE
  )

;;;; LATIN 3

(define-character-encoding :latin-3
  (:nicknames :latin3 :iso-8859-3 :iso8859-3)
  (:binary nil))

(define-unibyte-mapping :latin-3
  (#xA1 #x0126) ; LATIN CAPITAL LETTER H WITH STROKE
  (#xA2 #x02D8) ; BREVE
  (#xA5 nil)
  (#xA6 #x0124) ; LATIN CAPITAL LETTER H WITH CIRCUMFLEX
  (#xA9 #x0130) ; LATIN CAPITAL LETTER I WITH DOT ABOVE
  (#xAA #x015E) ; LATIN CAPITAL LETTER S WITH CEDILLA
  (#xAB #x011E) ; LATIN CAPITAL LETTER G WITH BREVE
  (#xAC #x0134) ; LATIN CAPITAL LETTER J WITH CIRCUMFLEX
  (#xAE nil)
  (#xAF #x017B) ; LATIN CAPITAL LETTER Z WITH DOT ABOVE
  (#xB1 #x0127) ; LATIN SMALL LETTER H WITH STROKE
  (#xB6 #x0125) ; LATIN SMALL LETTER H WITH CIRCUMFLEX
  (#xB9 #x0131) ; LATIN SMALL LETTER DOTLESS I
  (#xBA #x015F) ; LATIN SMALL LETTER S WITH CEDILLA
  (#xBB #x011F) ; LATIN SMALL LETTER G WITH BREVE
  (#xBC #x0135) ; LATIN SMALL LETTER J WITH CIRCUMFLEX
  (#xBE nil)
  (#xBF #x017C) ; LATIN SMALL LETTER Z WITH DOT ABOVE
  (#xC3 nil)
  (#xC5 #x010A) ; LATIN CAPITAL LETTER C WITH DOT ABOVE
  (#xC6 #x0108) ; LATIN CAPITAL LETTER C WITH CIRCUMFLEX
  (#xD0 nil)
  (#xD5 #x0120) ; LATIN CAPITAL LETTER G WITH DOT ABOVE
  (#xD8 #x011C) ; LATIN CAPITAL LETTER G WITH CIRCUMFLEX
  (#xDD #x016C) ; LATIN CAPITAL LETTER U WITH BREVE
  (#xDE #x015C) ; LATIN CAPITAL LETTER S WITH CIRCUMFLEX
  (#xE3 nil)
  (#xE5 #x010B) ; LATIN SMALL LETTER C WITH DOT ABOVE
  (#xE6 #x0109) ; LATIN SMALL LETTER C WITH CIRCUMFLEX
  (#xF0 nil)
  (#xF5 #x0121) ; LATIN SMALL LETTER G WITH DOT ABOVE
  (#xF8 #x011D) ; LATIN SMALL LETTER G WITH CIRCUMFLEX
  (#xFD #x016D) ; LATIN SMALL LETTER U WITH BREVE
  (#xFE #x015D) ; LATIN SMALL LETTER S WITH CIRCUMFLEX
  (#xFF #x02D9) ; DOT ABOVE
  )

;;;; LATIN 4

(define-character-encoding :latin-4
  (:nicknames :latin4 :iso-8859-4 :iso8859-4)
  (:binary t))

(define-unibyte-mapping :latin-4
  (#xA1 #x0104) ; LATIN CAPITAL LETTER A WITH OGONEK
  (#xA2 #x0138) ; LATIN SMALL LETTER KRA
  (#xA3 #x0156) ; LATIN CAPITAL LETTER R WITH CEDILLA
  (#xA5 #x0128) ; LATIN CAPITAL LETTER I WITH TILDE
  (#xA6 #x013B) ; LATIN CAPITAL LETTER L WITH CEDILLA
  (#xA9 #x0160) ; LATIN CAPITAL LETTER S WITH CARON
  (#xAA #x0112) ; LATIN CAPITAL LETTER E WITH MACRON
  (#xAB #x0122) ; LATIN CAPITAL LETTER G WITH CEDILLA
  (#xAC #x0166) ; LATIN CAPITAL LETTER T WITH STROKE
  (#xAE #x017D) ; LATIN CAPITAL LETTER Z WITH CARON
  (#xB1 #x0105) ; LATIN SMALL LETTER A WITH OGONEK
  (#xB2 #x02DB) ; OGONEK
  (#xB3 #x0157) ; LATIN SMALL LETTER R WITH CEDILLA
  (#xB5 #x0129) ; LATIN SMALL LETTER I WITH TILDE
  (#xB6 #x013C) ; LATIN SMALL LETTER L WITH CEDILLA
  (#xB7 #x02C7) ; CARON
  (#xB9 #x0161) ; LATIN SMALL LETTER S WITH CARON
  (#xBA #x0113) ; LATIN SMALL LETTER E WITH MACRON
  (#xBB #x0123) ; LATIN SMALL LETTER G WITH CEDILLA
  (#xBC #x0167) ; LATIN SMALL LETTER T WITH STROKE
  (#xBD #x014A) ; LATIN CAPITAL LETTER ENG
  (#xBE #x017E) ; LATIN SMALL LETTER Z WITH CARON
  (#xBF #x014B) ; LATIN SMALL LETTER ENG
  (#xC0 #x0100) ; LATIN CAPITAL LETTER A WITH MACRON
  (#xC7 #x012E) ; LATIN CAPITAL LETTER I WITH OGONEK
  (#xC8 #x010C) ; LATIN CAPITAL LETTER C WITH CARON
  (#xCA #x0118) ; LATIN CAPITAL LETTER E WITH OGONEK
  (#xCC #x0116) ; LATIN CAPITAL LETTER E WITH DOT ABOVE
  (#xCF #x012A) ; LATIN CAPITAL LETTER I WITH MACRON
  (#xD0 #x0110) ; LATIN CAPITAL LETTER D WITH STROKE
  (#xD1 #x0145) ; LATIN CAPITAL LETTER N WITH CEDILLA
  (#xD2 #x014C) ; LATIN CAPITAL LETTER O WITH MACRON
  (#xD3 #x0136) ; LATIN CAPITAL LETTER K WITH CEDILLA
  (#xD9 #x0172) ; LATIN CAPITAL LETTER U WITH OGONEK
  (#xDD #x0168) ; LATIN CAPITAL LETTER U WITH TILDE
  (#xDE #x016A) ; LATIN CAPITAL LETTER U WITH MACRON
  (#xE0 #x0101) ; LATIN SMALL LETTER A WITH MACRON
  (#xE7 #x012F) ; LATIN SMALL LETTER I WITH OGONEK
  (#xE8 #x010D) ; LATIN SMALL LETTER C WITH CARON
  (#xEA #x0119) ; LATIN SMALL LETTER E WITH OGONEK
  (#xEC #x0117) ; LATIN SMALL LETTER E WITH DOT ABOVE
  (#xEF #x012B) ; LATIN SMALL LETTER I WITH MACRON
  (#xF0 #x0111) ; LATIN SMALL LETTER D WITH STROKE
  (#xF1 #x0146) ; LATIN SMALL LETTER N WITH CEDILLA
  (#xF2 #x014D) ; LATIN SMALL LETTER O WITH MACRON
  (#xF3 #x0137) ; LATIN SMALL LETTER K WITH CEDILLA
  (#xF9 #x0173) ; LATIN SMALL LETTER U WITH OGONEK
  (#xFD #x0169) ; LATIN SMALL LETTER U WITH TILDE
  (#xFE #x016B) ; LATIN SMALL LETTER U WITH MACRON
  (#xFF #x02D9) ; DOT ABOVE
  )

;;;; LATIN 5

(define-character-encoding :latin-5
  (:nicknames :latin5 :iso-8859-9 :iso8859-9)
  (:binary t))

(define-unibyte-mapping :latin-5
  (#xD0 #x011E) ; LATIN CAPITAL LETTER G WITH BREVE
  (#xDD #x0130) ; LATIN CAPITAL LETTER I WITH DOT ABOVE
  (#xDE #x015E) ; LATIN CAPITAL LETTER S WITH CEDILLA
  (#xF0 #x011F) ; LATIN SMALL LETTER G WITH BREVE
  (#xFD #x0131) ; LATIN SMALL LETTER DOTLESS I
  (#xFE #x015F) ; LATIN SMALL LETTER S WITH CEDILLA
  )

;;;; LATIN 6

(define-character-encoding :latin-6
  (:nicknames :latin6 :iso-8859-10 :iso8859-10)
  (:binary t))

(define-unibyte-mapping :latin-6
  (#xA1 #x0104) ; LATIN CAPITAL LETTER A WITH OGONEK
  (#xA2 #x0112) ; LATIN CAPITAL LETTER E WITH MACRON
  (#xA3 #x0122) ; LATIN CAPITAL LETTER G WITH CEDILLA
  (#xA4 #x012A) ; LATIN CAPITAL LETTER I WITH MACRON
  (#xA5 #x0128) ; LATIN CAPITAL LETTER I WITH TILDE
  (#xA6 #x0136) ; LATIN CAPITAL LETTER K WITH CEDILLA
  (#xA8 #x013B) ; LATIN CAPITAL LETTER L WITH CEDILLA
  (#xA9 #x0110) ; LATIN CAPITAL LETTER D WITH STROKE
  (#xAA #x0160) ; LATIN CAPITAL LETTER S WITH CARON
  (#xAB #x0166) ; LATIN CAPITAL LETTER T WITH STROKE
  (#xAC #x017D) ; LATIN CAPITAL LETTER Z WITH CARON
  (#xAE #x016A) ; LATIN CAPITAL LETTER U WITH MACRON
  (#xAF #x014A) ; LATIN CAPITAL LETTER ENG
  (#xB1 #x0105) ; LATIN SMALL LETTER A WITH OGONEK
  (#xB2 #x0113) ; LATIN SMALL LETTER E WITH MACRON
  (#xB3 #x0123) ; LATIN SMALL LETTER G WITH CEDILLA
  (#xB4 #x012B) ; LATIN SMALL LETTER I WITH MACRON
  (#xB5 #x0129) ; LATIN SMALL LETTER I WITH TILDE
  (#xB6 #x0137) ; LATIN SMALL LETTER K WITH CEDILLA
  (#xB8 #x013C) ; LATIN SMALL LETTER L WITH CEDILLA
  (#xB9 #x0111) ; LATIN SMALL LETTER D WITH STROKE
  (#xBA #x0161) ; LATIN SMALL LETTER S WITH CARON
  (#xBB #x0167) ; LATIN SMALL LETTER T WITH STROKE
  (#xBC #x017E) ; LATIN SMALL LETTER Z WITH CARON
  (#xBD #x2015) ; HORIZONTAL BAR
  (#xBE #x016B) ; LATIN SMALL LETTER U WITH MACRON
  (#xBF #x014B) ; LATIN SMALL LETTER ENG
  (#xC0 #x0100) ; LATIN CAPITAL LETTER A WITH MACRON
  (#xC7 #x012E) ; LATIN CAPITAL LETTER I WITH OGONEK
  (#xC8 #x010C) ; LATIN CAPITAL LETTER C WITH CARON
  (#xCA #x0118) ; LATIN CAPITAL LETTER E WITH OGONEK
  (#xCC #x0116) ; LATIN CAPITAL LETTER E WITH DOT ABOVE
  (#xD1 #x0145) ; LATIN CAPITAL LETTER N WITH CEDILLA
  (#xD2 #x014C) ; LATIN CAPITAL LETTER O WITH MACRON
  (#xD7 #x0168) ; LATIN CAPITAL LETTER U WITH TILDE
  (#xD9 #x0172) ; LATIN CAPITAL LETTER U WITH OGONEK
  (#xE0 #x0101) ; LATIN SMALL LETTER A WITH MACRON
  (#xE7 #x012F) ; LATIN SMALL LETTER I WITH OGONEK
  (#xE8 #x010D) ; LATIN SMALL LETTER C WITH CARON
  (#xEA #x0119) ; LATIN SMALL LETTER E WITH OGONEK
  (#xEC #x0117) ; LATIN SMALL LETTER E WITH DOT ABOVE
  (#xF1 #x0146) ; LATIN SMALL LETTER N WITH CEDILLA
  (#xF2 #x014D) ; LATIN SMALL LETTER O WITH MACRON
  (#xF7 #x0169) ; LATIN SMALL LETTER U WITH TILDE
  (#xF9 #x0173) ; LATIN SMALL LETTER U WITH OGONEK
  (#xFF #x0138) ; LATIN SMALL LETTER KRA
  )

;;;; LATIN 7

(define-character-encoding :latin-7
  (:nicknames :latin7 :iso-8859-13 :iso8859-13)
  (:binary t))

(define-unibyte-mapping :latin-7
  (#xA1 #x201D) ; RIGHT DOUBLE QUOTATION MARK
  (#xA5 #x201E) ; DOUBLE LOW-9 QUOTATION MARK
  (#xA8 #x00D8) ; LATIN CAPITAL LETTER O WITH STROKE
  (#xAA #x0156) ; LATIN CAPITAL LETTER R WITH CEDILLA
  (#xAF #x00C6) ; LATIN CAPITAL LETTER AE
  (#xB4 #x201C) ; LEFT DOUBLE QUOTATION MARK
  (#xB8 #x00F8) ; LATIN SMALL LETTER O WITH STROKE
  (#xBA #x0157) ; LATIN SMALL LETTER R WITH CEDILLA
  (#xBF #x00E6) ; LATIN SMALL LETTER AE
  (#xC0 #x0104) ; LATIN CAPITAL LETTER A WITH OGONEK
  (#xC1 #x012E) ; LATIN CAPITAL LETTER I WITH OGONEK
  (#xC2 #x0100) ; LATIN CAPITAL LETTER A WITH MACRON
  (#xC3 #x0106) ; LATIN CAPITAL LETTER C WITH ACUTE
  (#xC6 #x0118) ; LATIN CAPITAL LETTER E WITH OGONEK
  (#xC7 #x0112) ; LATIN CAPITAL LETTER E WITH MACRON
  (#xC8 #x010C) ; LATIN CAPITAL LETTER C WITH CARON
  (#xCA #x0179) ; LATIN CAPITAL LETTER Z WITH ACUTE
  (#xCB #x0116) ; LATIN CAPITAL LETTER E WITH DOT ABOVE
  (#xCC #x0122) ; LATIN CAPITAL LETTER G WITH CEDILLA
  (#xCD #x0136) ; LATIN CAPITAL LETTER K WITH CEDILLA
  (#xCE #x012A) ; LATIN CAPITAL LETTER I WITH MACRON
  (#xCF #x013B) ; LATIN CAPITAL LETTER L WITH CEDILLA
  (#xD0 #x0160) ; LATIN CAPITAL LETTER S WITH CARON
  (#xD1 #x0143) ; LATIN CAPITAL LETTER N WITH ACUTE
  (#xD2 #x0145) ; LATIN CAPITAL LETTER N WITH CEDILLA
  (#xD4 #x014C) ; LATIN CAPITAL LETTER O WITH MACRON
  (#xD8 #x0172) ; LATIN CAPITAL LETTER U WITH OGONEK
  (#xD9 #x0141) ; LATIN CAPITAL LETTER L WITH STROKE
  (#xDA #x015A) ; LATIN CAPITAL LETTER S WITH ACUTE
  (#xDB #x016A) ; LATIN CAPITAL LETTER U WITH MACRON
  (#xDD #x017B) ; LATIN CAPITAL LETTER Z WITH DOT ABOVE
  (#xDE #x017D) ; LATIN CAPITAL LETTER Z WITH CARON
  (#xE0 #x0105) ; LATIN SMALL LETTER A WITH OGONEK
  (#xE1 #x012F) ; LATIN SMALL LETTER I WITH OGONEK
  (#xE2 #x0101) ; LATIN SMALL LETTER A WITH MACRON
  (#xE3 #x0107) ; LATIN SMALL LETTER C WITH ACUTE
  (#xE6 #x0119) ; LATIN SMALL LETTER E WITH OGONEK
  (#xE7 #x0113) ; LATIN SMALL LETTER E WITH MACRON
  (#xE8 #x010D) ; LATIN SMALL LETTER C WITH CARON
  (#xEA #x017A) ; LATIN SMALL LETTER Z WITH ACUTE
  (#xEB #x0117) ; LATIN SMALL LETTER E WITH DOT ABOVE
  (#xEC #x0123) ; LATIN SMALL LETTER G WITH CEDILLA
  (#xED #x0137) ; LATIN SMALL LETTER K WITH CEDILLA
  (#xEE #x012B) ; LATIN SMALL LETTER I WITH MACRON
  (#xEF #x013C) ; LATIN SMALL LETTER L WITH CEDILLA
  (#xF0 #x0161) ; LATIN SMALL LETTER S WITH CARON
  (#xF1 #x0144) ; LATIN SMALL LETTER N WITH ACUTE
  (#xF2 #x0146) ; LATIN SMALL LETTER N WITH CEDILLA
  (#xF4 #x014D) ; LATIN SMALL LETTER O WITH MACRON
  (#xF8 #x0173) ; LATIN SMALL LETTER U WITH OGONEK
  (#xF9 #x0142) ; LATIN SMALL LETTER L WITH STROKE
  (#xFA #x015B) ; LATIN SMALL LETTER S WITH ACUTE
  (#xFB #x016B) ; LATIN SMALL LETTER U WITH MACRON
  (#xFD #x017C) ; LATIN SMALL LETTER Z WITH DOT ABOVE
  (#xFE #x017E) ; LATIN SMALL LETTER Z WITH CARON
  (#xFF #x2019) ; RIGHT SINGLE QUOTATION MARK
  )

;;;; LATIN 8

(define-character-encoding :latin-8
  (:nicknames :latin8 :iso-8859-14 :iso8859-14)
  (:binary t))

(define-unibyte-mapping :latin-8
  (#xA1 #x1E02) ; LATIN CAPITAL LETTER B WITH DOT ABOVE
  (#xA2 #x1E03) ; LATIN SMALL LETTER B WITH DOT ABOVE
  (#xA4 #x010A) ; LATIN CAPITAL LETTER C WITH DOT ABOVE
  (#xA5 #x010B) ; LATIN SMALL LETTER C WITH DOT ABOVE
  (#xA6 #x1E0A) ; LATIN CAPITAL LETTER D WITH DOT ABOVE
  (#xA8 #x1E80) ; LATIN CAPITAL LETTER W WITH GRAVE
  (#xAA #x1E82) ; LATIN CAPITAL LETTER W WITH ACUTE
  (#xAB #x1E0B) ; LATIN SMALL LETTER D WITH DOT ABOVE
  (#xAC #x1EF2) ; LATIN CAPITAL LETTER Y WITH GRAVE
  (#xAF #x0178) ; LATIN CAPITAL LETTER Y WITH DIAERESIS
  (#xB0 #x1E1E) ; LATIN CAPITAL LETTER F WITH DOT ABOVE
  (#xB1 #x1E1F) ; LATIN SMALL LETTER F WITH DOT ABOVE
  (#xB2 #x0120) ; LATIN CAPITAL LETTER G WITH DOT ABOVE
  (#xB3 #x0121) ; LATIN SMALL LETTER G WITH DOT ABOVE
  (#xB4 #x1E40) ; LATIN CAPITAL LETTER M WITH DOT ABOVE
  (#xB5 #x1E41) ; LATIN SMALL LETTER M WITH DOT ABOVE
  (#xB7 #x1E56) ; LATIN CAPITAL LETTER P WITH DOT ABOVE
  (#xB8 #x1E81) ; LATIN SMALL LETTER W WITH GRAVE
  (#xB9 #x1E57) ; LATIN SMALL LETTER P WITH DOT ABOVE
  (#xBA #x1E83) ; LATIN SMALL LETTER W WITH ACUTE
  (#xBB #x1E60) ; LATIN CAPITAL LETTER S WITH DOT ABOVE
  (#xBC #x1EF3) ; LATIN SMALL LETTER Y WITH GRAVE
  (#xBD #x1E84) ; LATIN CAPITAL LETTER W WITH DIAERESIS
  (#xBE #x1E85) ; LATIN SMALL LETTER W WITH DIAERESIS
  (#xBF #x1E61) ; LATIN SMALL LETTER S WITH DOT ABOVE
  (#xD0 #x0174) ; LATIN CAPITAL LETTER W WITH CIRCUMFLEX
  (#xD7 #x1E6A) ; LATIN CAPITAL LETTER T WITH DOT ABOVE
  (#xDE #x0176) ; LATIN CAPITAL LETTER Y WITH CIRCUMFLEX
  (#xF0 #x0175) ; LATIN SMALL LETTER W WITH CIRCUMFLEX
  (#xF7 #x1E6B) ; LATIN SMALL LETTER T WITH DOT ABOVE
  (#xFE #x0177) ; LATIN SMALL LETTER Y WITH CIRCUMFLEX
  )

;;;; LATIN 9

(define-character-encoding :latin-9
  (:nicknames :latin9 :iso-8859-15 :iso8859-15)
  (:binary t))

(define-unibyte-mapping :latin-9
  (#xA4 #x20AC)
  (#xA6 #x0160)
  (#xA8 #x0161)
  (#xB4 #x017D)
  (#xB8 #x017E)
  (#xBC #x0152)
  (#xBD #x0153)
  (#xBE #x0178))
